export enum SkillCategory {
  COMPUTER_SCIENCE = "COMPUTER_SCIENCE",
  BACKEND_DEVELOPMENT = "BACKEND_DEVELOPMENT",
  FRONTEND_DEVELOPMENT = "FRONTEND_DEVELOPMENT",
  PLATFORMS_TOOLS = "PLATFORMS_TOOLS",
}
